### ISSUE TITLE
Natural Language Interface Web Components

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-for-ai#18]
Placeholder epic, details TBD.

**Comment by jeffchew** [comment]
After multiple conversations, it was decided that the Watson Assistant team will be taking on the responsibility of delivering the Chat functionality as well as integration support for M2W3 teams before THINK 2024. This essentially can be removed as a phase 2 responsibility for the Carbon team, but can be considered in backlog for other contributors to take on, as I still see a potential need for this outside of THINK and also the M2W3 initial cohort within IBM Software.

**Comment by mattrosno** [comment]
@jeffchew thank you. I'll close this as "not planned" for the Carbon team. If the Watson Assistant wants to build open source, in this repo, we can get new issues going for that effort.
